### PR TITLE
Add ability to fetch a single share

### PR DESCRIPTION
**Pull request by santib**

### CODE REVIEW

**Comment by santib** [comment]
@hexgnu Hi, I think that having access to this endpoint is quite important, for example to make 1 API call to get the likes and comments instead of calling the other 2 methods separately.

**Comment by hexgnu** [comment]
I'll cut a version and ship it sometime today

Thanks!

**Comment by santib** [comment]
Awesome! Thanks :)

**Comment by grzuy** [comment]
Hi @hexgnu 

Sorry to bother, but any update on releasing this new addition?

Thanks in advance! :-)

**Comment by hexgnu** [comment]
Pushed a new version just now

Thanks!

**Comment by grzuy** [comment]
Thanks a lot!!

**Pull request merged**
